recommend/commute/urls.py
from django.urls import path

from . import views

app_name = 'commute'
urlpatterns = [
	# ex: /rank/
	path('', views.index, name='index'),
	path('walk/<str:start_code>/<str:end_code>', views.walk, name='walk'),
	path('bus/<str:start_code>/<str:end_code>', views.bus, name='bus'),
	path('drive/<str:start_code>/<str:end_code>', views.drive, name='drive'),
	path('bicycle/<str:start_code>/<str:end_code>', views.bicycle, name='bicycle')
]

recommend/echart/urls.py
from django.urls import path

from . import views

app_name = 'echart'
urlpatterns = [
	# ex: /echart/
	path('', views.index, name='index'),
	path('test', views.test, name='test'),
	# ex: /echart/echarts/
	path('echarts/', views.echarts, name='echarts'),
	path('pyechart/', views.pyechart, name='pyechart'),
	path('3d', views.threed, name='search_house')
]

recommend/recommend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('echart/', include('echart.urls')),
    path('search/', include('search.urls')),
    path('commute/', include('commute.urls')),
]

recommend/search/urls.py
from django.urls import path

from . import views

app_name = 'search'
urlpatterns = [
	# ex: /search/
	path('', views.index, name='index'),
	path('search_house/', views.search_house, name='search_house'),
]

recommend/search/models.py
from django.db import models

# Create your models here.
class House(models.Model):
	"""
	hosue_dict:房子url<f>房名<f>面积<f>楼^楼<f>室^厅<f>交通
	example:   //hz.ziroom.com/z/vr/61654409.html<f>友家·湘湖家园3居室-南卧<f>25.3<f>6^6<f>3^1<f>距1号线湘湖站直线602米
	"""
	house_url = models.CharField("房源url", max_length=200)
	house_title = models.CharField("房源名称", max_length=100)
	house_area = models.FloatField("面积")
	house_floor = models.CharField("楼层（6/6楼）", max_length=10)
	house_model = models.CharField("户型（3^1：三室一厅）", max_length=10)
	house_traffic = models.CharField("离附近交通位置", max_length=200)
	house_subway = models.CharField("所属地铁范围", max_length=200)
	house_geocode = models.CharField("小区所在经纬度", max_length=50)
	house_price = models.IntegerField("价格")
	house_rent = models.CharField("租赁方式(合租、整租)", max_length=20)
	class Meta:
		managed = False
		db_table = "search_house"

recommend/search/views.py
from django.shortcuts import render
from .models import House
import requests
from .util_class import UtilClass
from django.core.cache import cache
import pandas as pd
from sklearn.cluster import KMeans
import numpy as np
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
    # 房子查找页面的主页
    return render(request, 'search/index.html')

@csrf_exempt
def search_house(request):
    company, subway = request.POST['info'].split('+')
    md_key = f"{company}-{subway}"
    destination = UtilClass().getGeocode(company)
    if cache.has_key(md_key):
        houses = cache.get(md_key)
    else:
        houses = rate_the_house(destination, subway)
        cache.set(md_key, houses, 60 * 60)
    data = {'houses': houses, 'company_geocode': destination}
    return render(request, 'search/search_result.html', context=data)

def rate_the_house(destination, subway):
    """
    {'http://sh.ziroom.com/z/vr/62017852.html':['http://sh.ziroom.com/z/vr/62017852.html', '友家·唐家沙小区2居室-南卧', 11.1, '06^6',
    '2^1', '距1号线延长路站直线814米', '延长路', '121.465652,31.270571', 2690, '合租',驾车规划距离，驾车时间，公交规划距离，公交时间，步行规划距离，步行时间]}
    """
    navigation_data = []
    houses = []
    for house in get_house_data(subway):
        house_dict = {}
        house_dict['id'] = house.id
        house_dict['house_url'] = house.house_url
        house_dict['house_title'] = house.house_title
        house_dict['house_area'] = house.house_area
        house_dict['house_floor'] = house.house_floor
        house_dict['house_model'] = house.house_model
        house_dict['house_traffic'] = house.house_traffic
        house_dict['house_subway'] = house.house_subway
        house_dict['house_geocode'] = house.house_geocode
        house_dict['house_price'] = house.house_price
        house_dict['house_rent'] = house.house_rent
        DistanceAndTime = UtilClass().get_destination_and_time(house.house_geocode, destination)
        navigation_data.append(
            [
                DistanceAndTime[0]['results'][0]['distance'],
                DistanceAndTime[1]['results'][0]['distance'],
                DistanceAndTime[2]['results'][0]['distance'],
                house.house_area,
                house.house_price,
                get_KFC(house.house_geocode)
            ]
        )
        houses.append(house_dict)
    score = get_score(navigation_data)
    for i in range(len(houses)):
        houses[i]['house_score'] = score[i]
    return sorted(houses, key=lambda score: score['house_score'], reverse=True)

def get_house_data(subway):
    return House.objects.filter(house_subway=subway)[:20]

def get_KFC(geoCode, key_word=u'肯德基'):
    para = {'location': geoCode, 'city': '成都', 'keywords': key_word,
            'key': 'ff7c4d965be7bbfcf3e18cf034f4f033', 'radius': 3000}
    base = 'https://restapi.amap.com/v3/place/around?parameters '
    response = requests.get(base, para)
    return len(response.json()['pois'])


def get_score(data):
    """
    k_means算法：将各个维度的数据分为三类
    """
    rates = {
        '驾车距离': 10,
        '步行距离': 20,
        '公交距离': 5,
        '价格': 20,
        '房间大小': 30,
        '周边繁华度': 10
    }
    load_data = pd.DataFrame(data)
    score = []
    for i in range(5):
        loan = np.array(load_data[[0]])
        clf = KMeans(n_clusters=3)
        clf = clf.fit(loan)
        min_label = list(clf.cluster_centers_).index(min(clf.cluster_centers_)) if i != 3 else list(
            clf.cluster_centers_).index(max(clf.cluster_centers_))
        max_label = list(clf.cluster_centers_).index(max(clf.cluster_centers_)) if i != 3 else list(
            clf.cluster_centers_).index(min(clf.cluster_centers_))
        for index in range(len(clf.labels_)):
            if clf.labels_[index] == min_label:
                clf.labels_[index] = 9
            elif clf.labels_[index] == max_label:
                clf.labels_[index] = 7
            else:
                clf.labels_[index] = 8
        load_data['label_' + str(i + 1)] = clf.labels_

    for i in range(len(load_data)):
        tmp_score = rates['驾车距离'] * (load_data['label_1'][i] - 6) + \
                    rates['公交距离'] * (load_data['label_2'][i] - 6) + \
                    rates['步行距离'] * (load_data['label_3'][i] - 6) + \
                    rates['价格'] * (load_data['label_4'][i] - 6) + \
                    rates['房间大小'] * (load_data['label_5'][i] - 6) + \
                    rates['周边繁华度'] * load_data[5][i]
        score.append(tmp_score)
    return score

recommend/search/templates/search/index.html
{% load static %}
<!doctype html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<title>房源搜索</title>
<link rel="stylesheet" type="text/css" href="{% static 'search/css/default.css'%}">
<link rel="stylesheet" type="text/css" href="{% static 'search/css/search-form.css'%}">
</head>
<body>
	<form action="{% url 'search:search_house'%}" method="post">
        {% csrf_token %}
		<div class="search-wrapper">
			<div class="input-holder">
				<input type="text" class="search-input" placeholder="Type to search" name="info"/>
				<button class="search-icon" onclick="searchToggle(this, event);"><span></span></button>
			</div>
			<span class="close" onclick="searchToggle(this, event);"></span>
			<div class="result-container">
			</div>
		</div>
	</form>
<script src="{% static 'search/js/jquery-1.11.0.min.js'%}" type="text/javascript"></script>
<script type="text/javascript">
	function searchToggle(obj, evt){
		var container = $(obj).closest('.search-wrapper');
		if(!container.hasClass('active')){
			  container.addClass('active');
			  evt.preventDefault();
		}
		else if(container.hasClass('active') && $(obj).closest('.input-holder').length == 0){
			  container.removeClass('active');
			  // clear input
			  container.find('.search-input').val('');
			  // clear and hide result container when we press close
			  container.find('.result-container').fadeOut(100, function(){$(this).empty();});
		}
	}
	function submitFn(obj, evt){
		value = $(obj).find('.search-input').val().trim();
		_html = "Yup yup! Your search text sounds like this: ";
		if(!value.length){
			_html = "Yup yup! Add some text friend :D";
		}
		else{
			_html += "<b>" + value + "</b>";
		}
		$(obj).find('.result-container').html('<span>' + _html + '</span>');
		$(obj).find('.result-container').fadeIn(100);
		evt.preventDefault();
	}
</script>
</body>
</html>

recommend/search/templates/search/search_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style type="text/css">
    * {
        margin: 0;
        padding: 0;
        list-style: none;
        text-decoration: none;
    }

    #dh {
        height: 30px;
        width: 600px;
        margin-top: 0;
        margin-right: auto;
        margin-bottom: 0;
        margin-left: auto;
    }

    table.hovertable {
        font-family: verdana, arial, sans-serif;
        font-size: 11px;
        color: #333333;
        margin-top: 30px;
        border-width: 1px;
        border-color: #81db34;
        border-collapse: collapse;
    }

    table.hovertable th {
        background-color: #c7254e;
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #FFFFFF;
    }

    table.hovertable tr {
        background-color: #FFFFFF;
    }

    table.hovertable td {
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #000000;
        white-space: nowrap;
    }
</style>
<body>
<div id="dh">
    <table class="hovertable">
        <tr>
            <th>得分</th>
            <th>小区</th>
            <th>价格</th>
            <th>URL</th>
            <th>面积</th>
            <th>楼层</th>
            <th>租赁方式</th>
            <th>骑车路径规划</th>
            <th>步行路径规划</th>
            <th>公交路径规划</th>
            <th>驾车路径规划</th>
        </tr>
        {% for house in houses %}
            <tr onmouseover="this.style.backgroundColor='#d58512';" onmouseout="this.style.backgroundColor='#FFFFFF';">
                <td>{{ house.house_score }}</td>
                <td>{{ house.house_title }}</td>
                <td>{{ house.house_price }}</td>
                <td><a href="{{ house.house_url }} " target="_blank">查看</a></td>
                <td>{{ house.house_area }}</td>
                <td>{{ house.house_floor }}</td>
                <td>{{ house.house_rent }}</td>
                <td><a href="{% url 'commute:bicycle' house.house_geocode company_geocode %}" target="_blank">骑自行车</a></td>
                <td><a href="{% url 'commute:walk' house.house_geocode company_geocode %}" target="_blank">走路</a></td>
                <td><a href="{% url 'commute:bus' house.house_geocode company_geocode %}" target="_blank">公交</a></td>
                <td><a href="{% url 'commute:drive' house.house_geocode company_geocode %}" target="_blank">开车</a></td>
                {#            [116.399028, 39.845042], [116.436281, 39.880719]#}
            </tr>
        {% endfor %}
    </table>
</div>
</body>
</html>

recommend/search/templates/search/test.html
{{ houses }}
{{ location }}