recommend/echart/urls.py
from django.urls import path

from . import views

app_name = 'echart'
urlpatterns = [
	# ex: /echart/
	path('', views.index, name='index'),
	path('test', views.test, name='test'),
	# ex: /echart/echarts/
	path('echarts/', views.echarts, name='echarts'),
	path('pyechart/', views.pyechart, name='pyechart'),
	path('3d', views.threed, name='search_house')
]

recommend/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('single/', views.single, name='single'),
]

recommend/recommend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('echart/', include('echart.urls')),
    path('search/', include('search.urls')),
    path('commute/', include('commute.urls')),
]

recommend/search/urls.py
from django.urls import path

from . import views

app_name = 'search'
urlpatterns = [
	# ex: /search/
	path('', views.index, name='index'),
	path('search_house/', views.search_house, name='search_house'),
]

recommend/homepage/models.py
from django.db import models

# Create your models here.

recommend/homepage/views.py
from django.shortcuts import render
from django.db.models import Sum
from django.db.models import Avg
from search.models import House

# Create your views here.
def index(request):
	return render(request, 'homepage/index.html')

def about(request):
	return render(request, 'person/about.html')

def contact(request):
	return render(request, 'person/contact.html')

def single(request):
	all_house = len(House.objects.all())
	zhengzu_house = len(House.objects.filter(house_rent="整租"))
	hezu_house = len(House.objects.filter(house_rent="合租"))
	all_avg = House.objects.all().aggregate(Avg('house_price'))
	ave_price = House.objects.filter(house_rent='整租').aggregate(Avg('house_price'))
	ave_pricetwo = House.objects.filter(house_rent='合租').aggregate(Avg('house_price'))
	scale_zheng = round(zhengzu_house / all_house, 3) * 100
	scale_he = round(hezu_house / all_house, 3) * 100
	data = {
		'all_house': all_house,
		'zhengzu_house': zhengzu_house,
		'hezu_house': hezu_house,
		'ave_price': ave_price,
		'ave_pricetwo': ave_pricetwo,
		'all_avg': all_avg,
		'scale_zheng': scale_zheng,
		'scale_he': scale_he}
	return render(request, 'person/single.html', context=data)

recommend/homepage/templates/homepage/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!--========== The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags ==========-->
<title>Chivalric</title>

<!--==========Dependency============-->
<link rel="stylesheet" href="{% static 'person/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'person/css/font-awesome.min.css' %}">
<link rel="stylesheet" href="{% static 'person/vendors/owl-carousel/assets/owl.carousel.css' %}">
<link rel="stylesheet" href="{% static 'person/vendors/magnific-popup/magnific-popup.css' %}">


<!--==========Theme Styles==========-->
<link href="{% static 'person/css/style.css' %}" rel="stylesheet">
<link href="{% static 'person/css/theme/green.css' %}" rel="stylesheet">

<!--========== HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries ==========-->
<!--========== WARNING: Respond.js doesn't work if you view the page via file:// ==========-->
<!--==========[if lt IE 9]>
    <script src="{% static 'person/js/html5shiv.min.js' %}"></script>
    <script src="{% static 'person/js/respond.min.js' %}"></script>
<![endif]==========-->
</head>
<body class="home">

<header class="row transparent white" data-spy="affix" data-offset-top="300" id="header">
    <div class="container">
        <div class="row top-header">
            <div class="col-sm-4 search-form-col">
                <form action="#" method="get" class="search-form">
                    <div class="input-group">
                        <span class="input-group-addon"><img src="{% static 'person/images/search-icon-dark.png' %}" alt=""></span>
                        <input type="search" class="form-control" placeholder="search">
                    </div>
                </form>
            </div>
            <div class="col-sm-4 logo-col text-center">
                <a href="{% url 'person:index' %}"><img src="{% static 'person/images/logo-black-green.png' %}" alt=""></a>
            </div>
            <div class="col-sm-4 menu-trigger-col">
                <button class="menu-trigger black pull-right">
                    <span class="active-page">About</span>
                    <img src="{% static 'person/images/menu-align-dark.png' %}" alt="" class="icon-burger">
                    <img src="{% static 'person/images/menu-close-dark.png' %}" alt="" class="icon-cross">
                </button>
            </div>
        </div>        
    </div>
    <div class="row menu-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 menu-col">
                    <div class="row">
                        <ul class="nav column-menu white-bg">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Home <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="index.html">Home Option 1</a></li>
                                    <li><a href="index2.html">Home Option 2</a></li>
                                    <li><a href="index3.html">Home Option 3</a></li>
                                    <li><a href="index4.html">Home Option 4</a></li>
                                    <li><a href="index5.html">Home Option 5</a></li>
                                    <li><a href="index6.html">Home Option 6</a></li>
                                </ul>
                            </li>
                            <li class="active"><a href="about.html">About</a></li>
                            <li><a href="single.html">Blog Single 1</a></li>
                            <li><a href="single2.html">Blog Single 2</a></li>
                        </ul>
                        <ul class="nav column-menu white-bg">
                            <li><a href="single3.html">Blog Single 3</a></li>
                            
                            <li><a href="contact.html">contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4 subscribe-col">
                    <h5 class="widget-title">subscribe to our newsletter.</h5>
                    <form action="#" method="post" class="form-inline subscribe-form">                    
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email">
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                    </form>
                    <ul class="nav social-nav white">
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>

<section class="row page-content-wrap">
    <div class="container">
        <h2 class="page-title text-center">about me</h2>
        <div class="row">
            <div class="col-md-8 page-contents">
                <div class="row page-content">
                    <img src="{% static 'person/images/author.jpg' %}" alt="" class="img-responsive">
                    
                    <div class="contents row">
                        <h4>Mark Samder, lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</h4>
                    
                        <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                        <br>
                        <div class="row">
                            <div class="col-sm-6">
                                <p>It has survived not only five centuries, remaining essentially unchanged. <a href="www.mywebsite.com">www.mywebsite.com</a> it was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                            </div>
                            <div class="col-sm-6">
                                <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="col-md-4 sidebar">  
                <!--Twitter Widget-->
                <aside class="row m0 widget widget-twitter">
                    <div class="widget-twitter-inner">
                        <h5 class="widget-meta"><i class="fa fa-github"></i> Github <a href="http://github.com/zhongyuhang">@zhongyuhang</a></h5>
                    </div>
                </aside>
                <!--Instagram Widget-->
                <aside class="row m0 widget widget-instagram">
                    <div class="widget-instagram-inner">
                        <h5 class="widget-meta"><i class="fa fa-twitter"></i>instagram feed <a href="http://twitter.com/chivalricblog">@chivalricblog</a></h5>
                        <div id="instafeed"></div>
                    </div>
                </aside>
                <aside class="row m0 widget widget-facebook">
                    <div class="widget-inner widget-facebook-inner">
                        <a href="#" class="facebook-link"><i class="fa fa-facebook-square"></i>find us on facebook</a>
                    </div>                    
                    <ul class="nav social-nav">
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i></a></li>
                    </ul>
                </aside>
            </div>
        </div>
    </div>
</section>

<!--Footer-->
<footer class="row" id="footer">
    <div class="container">
        <div class="row top-footer">
            <div class="widget col-sm-3 widget-about">
                <div class="row m0"><a href="{% url 'person:index' %}"><img src="{% static 'person/images/logo-black-green.png' %}" alt="">1</a></div>
            </div>
            <div class="widget col-sm-5 widget-menu">
                <div class="row">
                    <ul class="nav column-menu white-bg">
                        <li class="active"><a href="index.html">Home</a></li>
                        <li><a href="about.html">About</a></li>
                        <li><a href="single.html">Blog Single 1</a></li>
                        <li><a href="single2.html">Blog Single 2</a></li>
                    </ul>
                    <ul class="nav column-menu white-bg">
                        <li><a href="single3.html">Blog Single 3</a></li>

                        <li><a href="contact.html">contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="widget col-sm-4 widget-subscribe">
                <h5 class="widget-title">subscribe to our newsletter.</h5>
                <form action="#" method="post" class="form-inline subscribe-form">                    
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email">
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                </form>
            </div>
        </div>
    </div>
</footer>

<!--========== jQuery (necessary for Bootstrap's JavaScript plugins) ==========-->
<script src="{% static 'person/js/jquery-2.2.0.min.js' %}"></script>
<script src="{% static 'person/js/bootstrap.min.js' %}"></script>
<script src="{% static 'person/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'person/vendors/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'person/vendors/instafeed/instafeed.min.js' %}"></script>
<script src="{% static 'person/vendors/imagesLoaded/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'person/vendors/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'person/js/theme.js' %}"></script>
</body>
</html>

recommend/homepage/templates/homepage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--========== The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags ==========-->
    <title>HomePage</title>

    <!--==========Dependency============-->
    <link rel="stylesheet" href="{% static 'homepage/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/vendors/owl-carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'homepage/vendors/magnific-popup/magnific-popup.css' %}">


    <!--==========Theme Styles==========-->
    <link href="{% static 'homepage/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'homepage/css/theme/green.css' %}" rel="stylesheet">

    <!--========== HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries ==========-->
    <!--========== WARNING: Respond.js doesn't work if you view the page via file:// ==========-->
    <!--==========[if lt IE 9]>
    <script src="js/html5shiv.min.js"></script>
    <script src="js/respond.min.js"></script>
<![endif]==========-->
</head>
<body class="home">

<header class="row transparent black header1" data-spy="affix" data-offset-top="0" id="header">
    <div class="container">
        <div class="row top-header">
            <div class="col-sm-4 search-form-col">
                <form action="#" method="get" class="search-form">
                    <div class="input-group">
                        <span class="input-group-addon"></span>
                        <span type="search" class="form-control"></span>
                    </div>
                </form>
            </div>
            <div class="col-sm-4 logo-col text-center">
                <a href="{% url 'homepage:index' %}"><img src="{% static 'homepage/images/logo-white-green.png' %}" alt=""></a>
            </div>
            <div class="col-sm-4 menu-trigger-col">
                <button class="menu-trigger pull-right">
                    <span class="active-page">SEND ME</span>
                    <img src="{% static 'homepage/images/menu-align-white.png' %}" alt="" class="icon-burger">
                    <img src="{% static 'homepage/images/menu-close-white.png' %}" alt="" class="icon-cross">
                </button>
            </div>
        </div>
    </div>
    <div class="row menu-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 menu-col">
                    <div class="row">
                        <ul class="nav column-menu black-bg">
                            <li><a href="{% url 'search:index' %}">住房推荐</a></li>
                        </ul>
                        <ul class="nav column-menu black-bg">
                            <li><a href="{% url 'echart:index' %}">房源展示</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4 subscribe-col">
                    <h5 class="widget-title">subscribe to our newsletter.</h5>
                    <form action="#" method="post" class="form-inline subscribe-form">
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email">
                        </div>
                        <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                    </form>
                    <ul class="nav social-nav dark">
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>

<section class="row featured-post-carousel">
    <div class="item post">
        <img src="{% static 'homepage/images/featured-posts/1.jpg' %}" alt="" class="img-responsive main-bg">
        <div class="post-content">
            <div class="container">
                <h5 class="post-meta"><i>in</i> <a href="#">Me</a> | <a href="#">2019/2/27</a></h5>
                <h2 class="post-title"><a href="single.html">那会让租房变得更简单</a></h2>
                <a href="{% url 'search:index' %}" class="btn btn-primary"><span>点我看房</span></a>
            </div>
        </div>
    </div>
</section>
<section class="row content-wrap">
    <div class="container">
        <div class="row" id="post-masonry">
            <aside class="col-sm-4 widget-author widget widget-with-posts post">
                <div class="widget-author-inner row">
                    <div class="author-avatar row"><a href="#"><img src="{% static 'homepage/images/author.jpg' %}" alt=""
                                                                    class="img-circle"></a></div>
                    <a href="https://github.com/zhongyuhang"><h2 class="author-name">Shuang</h2></a>
                    <h5 class="author-title">GitHub</h5>
                    <p>Welcome to my github, hope can give me star</p>
                </div>
                <ul class="nav social-nav">
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-facebook-official"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                    <li><a href="#"><i class="fa fa-envelope"></i></a></li>
                </ul>
            </aside>
            <article class="col-sm-4 post post-masonry post-format-image">
                <div class="post-wrapper row">
                    <div class="featured-content row">
                        <a href="{% url 'echart:index' %}"><img src="{% static 'homepage/images/posts/masonry/上海数据.jpg' %}" alt=""
                                                   class="img-responsive"></a>
                    </div>
                    <div class="post-excerpt row">
                        <h5 class="post-meta">
                            <a href="#" class="date">{% now "SHORT_DATETIME_FORMAT" %}</a>
                            <span class="post-author"><i>by</i><a href="#">LS</a></span>
                        </h5>
                        <h3 class="post-title"><a href="{% url 'echart:pyechart' %}">数据可视化模块</a></h3>
                        <footer class="row">
                            <h5 class="taxonomy"><i>Go</i> <a href="https://maplab.amap.com/share/mapv/6495c897d36efaf9d7d5691d6cf5422b">and find it</a></h5>
                            <div class="response-count">
                            </div>
                        </footer>
                    </div>
                </div>
            </article>
        </div>
    </div>
</section>

<!--Footer-->
<footer class="row" id="footer">
    <div class="container">
        <div class="row top-footer">
            <div class="widget col-sm-3 widget-about">
                <div class="row m0"><a href="index.html"><img src="{% static 'homepage/images/logo-black-green.png' %}"
                                                              alt=""></a></div>
            </div>
            <div class="widget col-sm-5 widget-menu">
                <div class="row">
                    <ul class="nav column-menu white-bg">
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>
                    </ul>
                    <ul class="nav column-menu white-bg">
                        <li></li>
                        <li></li>
                    </ul>
                </div>
            </div>
            <div class="widget col-sm-4 widget-subscribe">
                <h5 class="widget-title">subscribe to our newsletter.</h5>
                <form action="#" method="post" class="form-inline subscribe-form">
                    <div class="form-group">
                        <input type="email" class="form-control" placeholder="Email">
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm"><span>send</span></button>
                </form>
            </div>
        </div>
    </div>
</footer>

<!--========== jQuery (necessary for Bootstrap's JavaScript plugins) ==========-->
<script src="{% static 'homepage/js/jquery-2.2.0.min.js' %}"></script>
<script src="{% static 'homepage/js/bootstrap.min.js' %}"></script>
<script src="{% static 'homepage/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'homepage/vendors/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'homepage/vendors/instafeed/instafeed.min.js' %}"></script>
<script src="{% static 'homepage/vendors/imagesLoaded/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'homepage/vendors/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'homepage/js/theme.js' %}"></script>
</body>
</html>

recommend/homepage/templates/homepage/single.html
{% load  static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>CSS3鼠标经过立体翻转切换特效</title>

    <link rel="stylesheet" href="{% static 'person/css/it/base.css' %}"/>
    <link rel="stylesheet" href="{% static 'person/css/it/style.css' %}"/>

    <script type="text/javascript" src="{% static 'person/js/it/jquery-1.7.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'person/js/it/global.js' %}"></script>

</head>
<body>

<div class="regularly-box">
    <div class="regularly-head">
        <strong>房源统计</strong>
    </div>
    <div class="regularly-contBody">
        <ul class="regularly-item-list">
            <li class="first viewport-flip">
                <div class="flip-box flip out">
                    <dl class="flip-lists">
                        <dd>
                            <i class="hot"></i>
                            <h3><b>整租套数</b></h3>
                            <div class="flip-itmes-info">
                                <strong>{{ scale_zheng }}%</strong>
                                <span class="to-day"><em>{{ zhengzu_house }}</em>套</span>
                                <div class="to-price">均价：<label>{{ ave_price.house_price__avg }}</label></div>
                            </div>
                        </dd>
                        <dd>
                            <h3>合租套数</h3>
                            <div class="flip-itmes-info">
                                <strong>{{ scale_he }}%</strong>
                                <span class="to-day"><em>{{ hezu_house }}</em>套</span>
                                <div class="to-price">均价：<label>{{ ave_pricetwo.house_price__avg }}</label>
                                </div>
                            </div>
                        </dd>
                        <dd>
                            <h3></h3>
                            <div class="flip-itmes-info">
                                <strong style="margin-left: auto;margin-right: auto">
                                    <a href="{% url 'search:index' %}">找房去</a>
                                </strong>
                            </div>
                        </dd>
                    </dl>
                </div>
                <div class="flip-box flip">
                    <div class="item-title">上海</div>
                    <div class="item-tx" style="color: #ac2925">房源数量：{{ all_house }}套</div>
                    <div class="item-tx" style="color: #ac2925">房源均价：<label>{{ all_avg.house_price__avg }}</label></div>
                    <div class="flip-foot">关键词：贵</div>
                </div>
            </li>
            <li class="viewport-flip">
                <div class="flip-box flip out">
                    <dl class="flip-lists">
                        <dd>
                            <i class="hot"></i>
                            <h3>整租套数</h3>
                            <div class="flip-itmes-info">
                                <strong>待开发</strong>
                                <span class="to-day"><em>待开发</em></span>
                                <div class="to-price">均价：<label>待开发</label></div>
                            </div>
                        </dd>
                        <dd>
                            <h3>合租套数</h3>
                            <div class="flip-itmes-info">
                                <strong>待开发</strong>
                                <span class="to-day"><em>待开发</em></span>
                                <div class="to-price">均价：<label>待开发</label></div>
                            </div>
                        </dd>
                        <dd>
                            <h3></h3>
                            <div class="flip-itmes-info">
                                <strong style="margin-left: auto;margin-right: auto">
                                    <a href="#">找房去</a>
                                </strong>
                            </div>
                        </dd>
                    </dl>
                </div>
                <div class="flip-box flip">
                    <div class="item-title">上海</div>
                    <div class="item-tx" style="color: #ac2925">房源数量：待开发</div>
                    <div class="item-tx" style="color: #ac2925">房源均价：<label>待开发</label></div>
                    <div class="flip-foot">关键词：待开发</div>
                </div>
            </li>
            <li class="last viewport-flip">
                <div class="flip-box flip out">
                    <dl class="flip-lists">
                        <dd>
                            <i class="hot"></i>
                            <h3>整租套数</h3>
                            <div class="flip-itmes-info">
                                <strong>待开发</strong>
                                <span class="to-day"><em>待开发</em></span>
                                <div class="to-price">均价：<label>待开发</label></div>
                            </div>
                        </dd>
                        <dd>
                            <h3>合租套数</h3>
                            <div class="flip-itmes-info">
                                <strong>待开发</strong>
                                <span class="to-day"><em>待开发</em>套</span>
                                <div class="to-price">均价：<label>待开发</label></div>
                            </div>
                        </dd>
                        <dd>
                            <h3></h3>
                            <div class="flip-itmes-info">
                                <strong style="margin-left: auto;margin-right: auto">
                                    <a href="#">找房去</a>
                                </strong>
                            </div>
                        </dd>
                    </dl>
                </div>
                <div class="flip-box flip">
                    <div class="item-title">上海</div>
                    <div class="item-tx" style="color: #ac2925">房源数量：待开发</div>
                    <div class="item-tx" style="color: #ac2925">房源均价：<label>待开发</label></div>
                    <div class="flip-foot">关键词：待开发</div>
                </div>
            </li>
        </ul>
    </div>
</div>

</body>
</html>